### ISSUE TITLE
[BUG] Mejorar código USSD para obtener la lista del plan amigos

### ISSUE THREAD

**Issue by leynier** [todo-devs/todo#14]
![image](https://user-images.githubusercontent.com/36774373/104277727-5641ed00-5475-11eb-819b-f10fe342e33b.png)

Mira, aquí en la opción de Plan Amigos, en el apartado de ver la lista de amigos, sería bueno que salga ya la lista directa, y no el menú de Cubacel, porque sino hay que estar escribiendo el 1 dos veces seguidas para poder llegar después a la lista de amigos.

**Comment by leynier** [comment]
@leynier @JoseKill09 👆

**Comment by leynier** [comment]
Actualmente se ejecuta `*133*4*3#` probar si puede ser `*133*4*3*1#`

**Comment by correaleyval** [comment]
@leynier Esto está listo lo que no he podido probar es que te deje cambiarlos, eso traga saldo 😅
