### ISSUE TITLE
[FEATURE] Actualizar automáticamente los códigos USSD una vez al día al abrir la aplicación

### ISSUE THREAD

**Issue by leynier** [todo-devs/todo#16]

**Comment by correaleyval** [comment]
Se hace la comprobación para actualizar cada vez que se abre la aplicación. Cuando no hay datos conectados el time out funciona perfecto, pero con los datos puestos si se establece la conexión se demora un poco en abrir la aplicación. Hay que implementar que la actualización se realice una sola vez al día y además mostrar un mensaje diferente para que el usuarios sepa cuando se está comprobando y actualizando los códigos.

**Comment by leynier** [comment]
> Se hace la comprobación para actualizar cada vez que se abre la aplicación. Cuando no hay datos conectados el time out funciona perfecto, pero con los datos puestos si se establece la conexión se demora un poco en abrir la aplicación. Hay que implementar que la actualización se realice una sola vez al día y además mostrar un mensaje diferente para que el usuarios sepa cuando se está comprobando y actualizando los códigos.

Dices que se demora un poco y que se debe mostrar un mensaje diferente al usuario? Precisamente esto, actualmente sale el cargando, dices crear un estado especial para cuando los códigos USSD se están actualizando? Respecto a lo de una vez en el día, Ok, hay que agregar unos servicios/repositorios para obtener y guardar el ultimo día en que se reviso, para si es diferente del día actual entonces lanzar la revisión/actualización de los códigos USSD.

**Comment by correaleyval** [comment]
@leynier Si, usar un estado diferente para informar cuando de están actualizando los códigos. Y almacenar el último día que se hizo la comprobación/actualización para que solo haga esta operación una vez al día.

**Comment by correaleyval** [comment]
Esto está listo, los códigos USSD se actualizan en segundo plano sin afectar la carga de los que ya estaban guardados anteriormente. Cierro el issue.
